### ISSUE TITLE
DellOS10 password encryption

### ISSUE THREAD

**Issue by benohara** [Dell-Networking/ansible-role-dellos-users#1]
Looks like the latest version of dellos10, 10.4.0E(R1) changes the password encryption.

    OS10(config)# username test password
       String  Password format <clear text password>(Hashed to SHA-512)
                      $<id>$<salt>$<password hash>

The plain test password needs setting without the $0$ prefix

**Comment by skg-net** [comment]
@benohara fixed in the latest release.
